CREATE TABLE IF NOT EXISTS `#__sensorsESP8266` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Arduino Sensor\nDHT 11-22 \n ESP8266 \ndsphinx@plug.gr',
  `temperature` FLOAT NOT NULL,
  `humidity` FLOAT NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT '',
  `clientIP` VARCHAR(15) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `dateEntry` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `deleted` BIT(1) NULL DEFAULT b'0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 0
DEFAULT CHARACTER SET = utf8;